-- ============================================================================
-- CH2OTEL: ClickHouse System Metrics to OpenTelemetry Converter
-- Version: 1.0.0
-- Generated: Auto-generated by setup-ch2otel.sh
-- ============================================================================
-- Description: Converts ClickHouse system metrics and logs to OTEL format
-- Scope: Single service only (self-service monitoring)
-- Requirements: ClickHouse Cloud with Refreshable Materialized Views support
-- ============================================================================

-- ============================================================================
-- PART 1: DATABASE SETUP
-- ============================================================================

CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};

-- ============================================================================
-- PART 2: OTEL STANDARD TABLES
-- ============================================================================

-- 2.1 otel_logs
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.otel_logs
(
    `Timestamp` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `TimestampTime` DateTime DEFAULT toDateTime(Timestamp),
    `TraceId` String CODEC(ZSTD(1)),
    `SpanId` String CODEC(ZSTD(1)),
    `TraceFlags` UInt8,
    `SeverityText` LowCardinality(String) CODEC(ZSTD(1)),
    `SeverityNumber` UInt8,
    `ServiceName` LowCardinality(String) CODEC(ZSTD(1)),
    `Body` String CODEC(ZSTD(1)),
    `ResourceSchemaUrl` LowCardinality(String) CODEC(ZSTD(1)),
    `ResourceAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ScopeSchemaUrl` LowCardinality(String) CODEC(ZSTD(1)),
    `ScopeName` String CODEC(ZSTD(1)),
    `ScopeVersion` LowCardinality(String) CODEC(ZSTD(1)),
    `ScopeAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `LogAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    INDEX idx_trace_id TraceId TYPE bloom_filter(0.001) GRANULARITY 1,
    INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_key mapKeys(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_value mapValues(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_log_attr_key mapKeys(LogAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_log_attr_value mapValues(LogAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_body Body TYPE tokenbf_v1(32768, 3, 0) GRANULARITY 8
)
ENGINE = SharedMergeTree
PARTITION BY toDate(TimestampTime)
PRIMARY KEY (ServiceName, TimestampTime)
ORDER BY (ServiceName, TimestampTime, Timestamp)
TTL toDate(TimestampTime) + INTERVAL ${DATA_RETENTION_DAYS} DAY;

-- 2.2 otel_traces
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.otel_traces
(
    `Timestamp` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `TraceId` String CODEC(ZSTD(1)),
    `SpanId` String CODEC(ZSTD(1)),
    `ParentSpanId` String CODEC(ZSTD(1)),
    `TraceState` String CODEC(ZSTD(1)),
    `SpanName` LowCardinality(String) CODEC(ZSTD(1)),
    `SpanKind` LowCardinality(String) CODEC(ZSTD(1)),
    `ServiceName` LowCardinality(String) CODEC(ZSTD(1)),
    `ResourceAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ScopeName` String CODEC(ZSTD(1)),
    `ScopeVersion` String CODEC(ZSTD(1)),
    `SpanAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `Duration` UInt64 CODEC(ZSTD(1)),
    `StatusCode` LowCardinality(String) CODEC(ZSTD(1)),
    `StatusMessage` String CODEC(ZSTD(1)),
    `Events.Timestamp` Array(DateTime64(9)) CODEC(ZSTD(1)),
    `Events.Name` Array(LowCardinality(String)) CODEC(ZSTD(1)),
    `Events.Attributes` Array(Map(LowCardinality(String), String)) CODEC(ZSTD(1)),
    `Links.TraceId` Array(String) CODEC(ZSTD(1)),
    `Links.SpanId` Array(String) CODEC(ZSTD(1)),
    `Links.TraceState` Array(String) CODEC(ZSTD(1)),
    `Links.Attributes` Array(Map(LowCardinality(String), String)) CODEC(ZSTD(1)),
    INDEX idx_trace_id TraceId TYPE bloom_filter(0.001) GRANULARITY 1,
    INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_span_attr_key mapKeys(SpanAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_span_attr_value mapValues(SpanAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_duration Duration TYPE minmax GRANULARITY 1
)
ENGINE = SharedMergeTree
PARTITION BY toDate(Timestamp)
ORDER BY (ServiceName, SpanName, toDateTime(Timestamp))
TTL toDate(Timestamp) + INTERVAL ${DATA_RETENTION_DAYS} DAY;

-- 2.3 otel_metrics_gauge
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.otel_metrics_gauge
(
    `ResourceAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ResourceSchemaUrl` String CODEC(ZSTD(1)),
    `ScopeName` String CODEC(ZSTD(1)),
    `ScopeVersion` String CODEC(ZSTD(1)),
    `ScopeAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ScopeDroppedAttrCount` UInt32 CODEC(ZSTD(1)),
    `ScopeSchemaUrl` String CODEC(ZSTD(1)),
    `ServiceName` LowCardinality(String) CODEC(ZSTD(1)),
    `MetricName` String CODEC(ZSTD(1)),
    `MetricDescription` String CODEC(ZSTD(1)),
    `MetricUnit` String CODEC(ZSTD(1)),
    `Attributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `StartTimeUnix` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `TimeUnix` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `Value` Float64 CODEC(ZSTD(1)),
    `Flags` UInt32 CODEC(ZSTD(1)),
    `Exemplars.FilteredAttributes` Array(Map(LowCardinality(String), String)) CODEC(ZSTD(1)),
    `Exemplars.TimeUnix` Array(DateTime64(9)) CODEC(ZSTD(1)),
    `Exemplars.Value` Array(Float64) CODEC(ZSTD(1)),
    `Exemplars.SpanId` Array(String) CODEC(ZSTD(1)),
    `Exemplars.TraceId` Array(String) CODEC(ZSTD(1)),
    INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_key mapKeys(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_value mapValues(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_attr_key mapKeys(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_attr_value mapValues(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = SharedMergeTree
PARTITION BY toDate(TimeUnix)
ORDER BY (ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
TTL toDate(TimeUnix) + INTERVAL ${DATA_RETENTION_DAYS} DAY;

-- 2.4 otel_metrics_sum
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.otel_metrics_sum
(
    `ResourceAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ResourceSchemaUrl` String CODEC(ZSTD(1)),
    `ScopeName` String CODEC(ZSTD(1)),
    `ScopeVersion` String CODEC(ZSTD(1)),
    `ScopeAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ScopeDroppedAttrCount` UInt32 CODEC(ZSTD(1)),
    `ScopeSchemaUrl` String CODEC(ZSTD(1)),
    `ServiceName` LowCardinality(String) CODEC(ZSTD(1)),
    `MetricName` String CODEC(ZSTD(1)),
    `MetricDescription` String CODEC(ZSTD(1)),
    `MetricUnit` String CODEC(ZSTD(1)),
    `Attributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `StartTimeUnix` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `TimeUnix` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `Value` Float64 CODEC(ZSTD(1)),
    `Flags` UInt32 CODEC(ZSTD(1)),
    `Exemplars.FilteredAttributes` Array(Map(LowCardinality(String), String)) CODEC(ZSTD(1)),
    `Exemplars.TimeUnix` Array(DateTime64(9)) CODEC(ZSTD(1)),
    `Exemplars.Value` Array(Float64) CODEC(ZSTD(1)),
    `Exemplars.SpanId` Array(String) CODEC(ZSTD(1)),
    `Exemplars.TraceId` Array(String) CODEC(ZSTD(1)),
    `AggregationTemporality` Int32 CODEC(ZSTD(1)),
    `IsMonotonic` Bool CODEC(Delta(1), ZSTD(1)),
    INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_key mapKeys(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_value mapValues(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_attr_key mapKeys(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_attr_value mapValues(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = SharedMergeTree
PARTITION BY toDate(TimeUnix)
ORDER BY (ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
TTL toDate(TimeUnix) + INTERVAL ${DATA_RETENTION_DAYS} DAY;

-- 2.5 otel_metrics_histogram
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.otel_metrics_histogram
(
    `ResourceAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ResourceSchemaUrl` String CODEC(ZSTD(1)),
    `ScopeName` String CODEC(ZSTD(1)),
    `ScopeVersion` String CODEC(ZSTD(1)),
    `ScopeAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ScopeDroppedAttrCount` UInt32 CODEC(ZSTD(1)),
    `ScopeSchemaUrl` String CODEC(ZSTD(1)),
    `ServiceName` LowCardinality(String) CODEC(ZSTD(1)),
    `MetricName` String CODEC(ZSTD(1)),
    `MetricDescription` String CODEC(ZSTD(1)),
    `MetricUnit` String CODEC(ZSTD(1)),
    `Attributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `StartTimeUnix` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `TimeUnix` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `Count` UInt64 CODEC(Delta(8), ZSTD(1)),
    `Sum` Float64 CODEC(ZSTD(1)),
    `BucketCounts` Array(UInt64) CODEC(ZSTD(1)),
    `ExplicitBounds` Array(Float64) CODEC(ZSTD(1)),
    `Exemplars.FilteredAttributes` Array(Map(LowCardinality(String), String)) CODEC(ZSTD(1)),
    `Exemplars.TimeUnix` Array(DateTime64(9)) CODEC(ZSTD(1)),
    `Exemplars.Value` Array(Float64) CODEC(ZSTD(1)),
    `Exemplars.SpanId` Array(String) CODEC(ZSTD(1)),
    `Exemplars.TraceId` Array(String) CODEC(ZSTD(1)),
    `Flags` UInt32 CODEC(ZSTD(1)),
    `Min` Float64 CODEC(ZSTD(1)),
    `Max` Float64 CODEC(ZSTD(1)),
    `AggregationTemporality` Int32 CODEC(ZSTD(1)),
    INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_key mapKeys(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_value mapValues(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_attr_key mapKeys(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_attr_value mapValues(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = SharedMergeTree
PARTITION BY toDate(TimeUnix)
ORDER BY (ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
TTL toDate(TimeUnix) + INTERVAL ${DATA_RETENTION_DAYS} DAY;

-- 2.6 otel_metrics_summary
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.otel_metrics_summary
(
    `ResourceAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ResourceSchemaUrl` String CODEC(ZSTD(1)),
    `ScopeName` String CODEC(ZSTD(1)),
    `ScopeVersion` String CODEC(ZSTD(1)),
    `ScopeAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ScopeDroppedAttrCount` UInt32 CODEC(ZSTD(1)),
    `ScopeSchemaUrl` String CODEC(ZSTD(1)),
    `ServiceName` LowCardinality(String) CODEC(ZSTD(1)),
    `MetricName` String CODEC(ZSTD(1)),
    `MetricDescription` String CODEC(ZSTD(1)),
    `MetricUnit` String CODEC(ZSTD(1)),
    `Attributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `StartTimeUnix` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `TimeUnix` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `Count` UInt64 CODEC(Delta(8), ZSTD(1)),
    `Sum` Float64 CODEC(ZSTD(1)),
    `ValueAtQuantiles.Quantile` Array(Float64) CODEC(ZSTD(1)),
    `ValueAtQuantiles.Value` Array(Float64) CODEC(ZSTD(1)),
    `Flags` UInt32 CODEC(ZSTD(1)),
    INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_key mapKeys(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_value mapValues(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_attr_key mapKeys(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_attr_value mapValues(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = SharedMergeTree
PARTITION BY toDate(TimeUnix)
ORDER BY (ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
TTL toDate(TimeUnix) + INTERVAL ${DATA_RETENTION_DAYS} DAY;

-- 2.7 otel_metrics_exponentialhistogram
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.otel_metrics_exponentialhistogram
(
    `ResourceAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ResourceSchemaUrl` String CODEC(ZSTD(1)),
    `ScopeName` String CODEC(ZSTD(1)),
    `ScopeVersion` String CODEC(ZSTD(1)),
    `ScopeAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ScopeDroppedAttrCount` UInt32 CODEC(ZSTD(1)),
    `ScopeSchemaUrl` String CODEC(ZSTD(1)),
    `ServiceName` LowCardinality(String) CODEC(ZSTD(1)),
    `MetricName` String CODEC(ZSTD(1)),
    `MetricDescription` String CODEC(ZSTD(1)),
    `MetricUnit` String CODEC(ZSTD(1)),
    `Attributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `StartTimeUnix` DateTime64(9) CODEC(Delta, ZSTD(1)),
    `TimeUnix` DateTime64(9) CODEC(Delta, ZSTD(1)),
    `Count` UInt64 CODEC(Delta, ZSTD(1)),
    `Sum` Float64 CODEC(ZSTD(1)),
    `Scale` Int32 CODEC(ZSTD(1)),
    `ZeroCount` UInt64 CODEC(ZSTD(1)),
    `PositiveOffset` Int32 CODEC(ZSTD(1)),
    `PositiveBucketCounts` Array(UInt64) CODEC(ZSTD(1)),
    `NegativeOffset` Int32 CODEC(ZSTD(1)),
    `NegativeBucketCounts` Array(UInt64) CODEC(ZSTD(1)),
    `Exemplars.FilteredAttributes` Array(Map(LowCardinality(String), String)) CODEC(ZSTD(1)),
    `Exemplars.TimeUnix` Array(DateTime64(9)) CODEC(ZSTD(1)),
    `Exemplars.Value` Array(Float64) CODEC(ZSTD(1)),
    `Exemplars.SpanId` Array(String) CODEC(ZSTD(1)),
    `Exemplars.TraceId` Array(String) CODEC(ZSTD(1)),
    `Flags` UInt32 CODEC(ZSTD(1)),
    `Min` Float64 CODEC(ZSTD(1)),
    `Max` Float64 CODEC(ZSTD(1)),
    `AggregationTemporality` Int32 CODEC(ZSTD(1)),
    INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_key mapKeys(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_value mapValues(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_attr_key mapKeys(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_attr_value mapValues(Attributes) TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = SharedMergeTree
PARTITION BY toDate(TimeUnix)
ORDER BY (ServiceName, MetricName, Attributes, toUnixTimestamp64Nano(TimeUnix))
TTL toDate(TimeUnix) + INTERVAL ${DATA_RETENTION_DAYS} DAY;

-- 2.8 hyperdx_sessions
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.hyperdx_sessions
(
    `Timestamp` DateTime64(9) CODEC(Delta(8), ZSTD(1)),
    `TimestampTime` DateTime DEFAULT toDateTime(Timestamp),
    `TraceId` String CODEC(ZSTD(1)),
    `SpanId` String CODEC(ZSTD(1)),
    `TraceFlags` UInt8,
    `SeverityText` LowCardinality(String) CODEC(ZSTD(1)),
    `SeverityNumber` UInt8,
    `ServiceName` LowCardinality(String) CODEC(ZSTD(1)),
    `Body` String CODEC(ZSTD(1)),
    `ResourceSchemaUrl` LowCardinality(String) CODEC(ZSTD(1)),
    `ResourceAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `ScopeSchemaUrl` LowCardinality(String) CODEC(ZSTD(1)),
    `ScopeName` String CODEC(ZSTD(1)),
    `ScopeVersion` LowCardinality(String) CODEC(ZSTD(1)),
    `ScopeAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    `LogAttributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    INDEX idx_trace_id TraceId TYPE bloom_filter(0.001) GRANULARITY 1,
    INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_key mapKeys(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_scope_attr_value mapValues(ScopeAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_log_attr_key mapKeys(LogAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_log_attr_value mapValues(LogAttributes) TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_body Body TYPE tokenbf_v1(32768, 3, 0) GRANULARITY 8
)
ENGINE = SharedMergeTree
PARTITION BY toDate(TimestampTime)
PRIMARY KEY (ServiceName, TimestampTime)
ORDER BY (ServiceName, TimestampTime, Timestamp)
TTL toDate(TimestampTime) + INTERVAL ${DATA_RETENTION_DAYS} DAY;

-- ============================================================================
-- PART 3: REFRESHABLE MATERIALIZED VIEWS - LOGS
-- ============================================================================

-- 3.1 rmv_part_logs - Part Events to Logs
CREATE MATERIALIZED VIEW IF NOT EXISTS ${DATABASE_NAME}.rmv_part_logs
REFRESH EVERY ${REFRESH_INTERVAL_MINUTES} MINUTE APPEND
TO ${DATABASE_NAME}.otel_logs
AS
SELECT
    toDateTime64(event_time_microseconds, 9) AS Timestamp,
    toDateTime(event_time_microseconds) AS TimestampTime,
    query_id AS TraceId,
    toString(table_uuid) AS SpanId,
    toUInt8(1) AS TraceFlags,
    if(error = 0, 'INFO', 'ERROR') AS SeverityText,
    if(error = 0, toUInt8(9), toUInt8(17)) AS SeverityNumber,
    concat(database, '.', `table`) AS ServiceName,
    concat(toString(event_type), ': ', database, '.', `table`,
           ' | part=', part_name,
           ' | rows=', toString(rows),
           ' | duration=', toString(duration_ms), 'ms',
           if(exception != '', concat(' | error=', substring(exception, 1, 200)), '')) AS Body,
    '' AS ResourceSchemaUrl,
    map('service.name', concat(database, '.', `table`),
        'service.version', '1.0.0',
        'deployment.environment', 'production',
        'clickhouse.service_id', extract(hostname(), 'c-([a-z]+-[a-z]+-[0-9]+)'),
        'clickhouse.replica', getMacro('replica'),
        'clickhouse.hostname', hostname(),
        'rum.sessionId', concat('pipeline_', database, '_', toString(toDate(event_time_microseconds)))) AS ResourceAttributes,
    '' AS ScopeSchemaUrl,
    'ingest-monitor' AS ScopeName,
    '1.0.0' AS ScopeVersion,
    map() AS ScopeAttributes,
    map('database', database,
        'table', `table`,
        'part_name', part_name,
        'event_type', toString(event_type),
        'rows', toString(rows),
        'size_bytes', toString(size_in_bytes),
        'duration_ms', toString(duration_ms),
        'peak_memory_usage', toString(peak_memory_usage),
        'query_id', query_id,
        'disk_name', disk_name,
        'pipeline_type', 'part_event') AS LogAttributes
FROM system.part_log
WHERE event_time >= now() - INTERVAL ${LOOKBACK_INTERVAL_MINUTES} MINUTE
  AND database NOT IN ('system', 'INFORMATION_SCHEMA', 'information_schema', '${DATABASE_NAME}')
  AND event_type IN ('NewPart', 'MergeParts');

-- 3.2 rmv_mview_logs - MView Executions to Logs
CREATE MATERIALIZED VIEW IF NOT EXISTS ${DATABASE_NAME}.rmv_mview_logs
REFRESH EVERY ${REFRESH_INTERVAL_MINUTES} MINUTE APPEND
TO ${DATABASE_NAME}.otel_logs
AS
SELECT
    toDateTime64(event_time_microseconds, 9) AS Timestamp,
    toDateTime(event_time_microseconds) AS TimestampTime,
    initial_query_id AS TraceId,
    toString(view_uuid) AS SpanId,
    toUInt8(1) AS TraceFlags,
    multiIf(
        status = 'QueryFinish', 'INFO',
        status IN ('ExceptionWhileProcessing', 'ExceptionBeforeStart'), 'ERROR',
        'WARN'
    ) AS SeverityText,
    multiIf(
        status = 'QueryFinish', toUInt8(9),
        status IN ('ExceptionWhileProcessing', 'ExceptionBeforeStart'), toUInt8(17),
        toUInt8(13)
    ) AS SeverityNumber,
    view_name AS ServiceName,
    concat('MView ', toString(status), ': ', view_name,
           ' | rows=', toString(written_rows),
           ' | duration=', toString(view_duration_ms), 'ms',
           if(exception != '', concat(' | error=', substring(exception, 1, 200)), '')) AS Body,
    '' AS ResourceSchemaUrl,
    map('service.name', view_name,
        'service.version', '1.0.0',
        'deployment.environment', 'production',
        'clickhouse.service_id', extract(hostname(), 'c-([a-z]+-[a-z]+-[0-9]+)'),
        'clickhouse.replica', getMacro('replica'),
        'clickhouse.hostname', hostname(),
        'rum.sessionId', concat('pipeline_', splitByChar('.', view_name)[1], '_', toString(toDate(event_time_microseconds)))) AS ResourceAttributes,
    '' AS ScopeSchemaUrl,
    'ingest-monitor' AS ScopeName,
    '1.0.0' AS ScopeVersion,
    map() AS ScopeAttributes,
    map('view_name', view_name,
        'view_target', view_target,
        'status', toString(status),
        'duration_ms', toString(view_duration_ms),
        'written_rows', toString(written_rows),
        'written_bytes', toString(written_bytes),
        'read_rows', toString(read_rows),
        'read_bytes', toString(read_bytes),
        'peak_memory_usage', toString(peak_memory_usage),
        'query_id', initial_query_id,
        'pipeline_type', 'mview') AS LogAttributes
FROM system.query_views_log
WHERE event_time >= now() - INTERVAL ${LOOKBACK_INTERVAL_MINUTES} MINUTE
  AND view_type = 'Materialized';

-- 3.3 rmv_status_logs - RMV Status to Logs
CREATE MATERIALIZED VIEW IF NOT EXISTS ${DATABASE_NAME}.rmv_status_logs
REFRESH EVERY ${REFRESH_INTERVAL_MINUTES} MINUTE APPEND
TO ${DATABASE_NAME}.otel_logs
AS
SELECT
    now64(9) AS Timestamp,
    toDateTime(now()) AS TimestampTime,
    lower(hex(MD5(concat(database, '.', view, toString(toDate(now())))))) AS TraceId,
    toString(uuid) AS SpanId,
    toUInt8(1) AS TraceFlags,
    multiIf(
        exception != '', 'ERROR',
        status = 'Scheduled' AND next_refresh_time < now(), 'WARN',
        'INFO'
    ) AS SeverityText,
    multiIf(
        exception != '', toUInt8(17),
        status = 'Scheduled' AND next_refresh_time < now(), toUInt8(13),
        toUInt8(9)
    ) AS SeverityNumber,
    concat(database, '.', view) AS ServiceName,
    concat('RMV Status: ', database, '.', view,
           ' | status=', status,
           ' | last_success=', toString(assumeNotNull(last_success_time)),
           ' | next=', toString(assumeNotNull(next_refresh_time)),
           if(exception != '', concat(' | error=', substring(exception, 1, 200)), '')) AS Body,
    '' AS ResourceSchemaUrl,
    map('service.name', concat(database, '.', view),
        'service.version', '1.0.0',
        'deployment.environment', 'production',
        'clickhouse.service_id', extract(hostname(), 'c-([a-z]+-[a-z]+-[0-9]+)'),
        'clickhouse.replica', getMacro('replica'),
        'clickhouse.hostname', hostname(),
        'rum.sessionId', concat('pipeline_', database, '_', toString(toDate(now())))) AS ResourceAttributes,
    '' AS ScopeSchemaUrl,
    'ingest-monitor' AS ScopeName,
    '1.0.0' AS ScopeVersion,
    map() AS ScopeAttributes,
    map('database', database,
        'view', view,
        'status', status,
        'last_success_time', toString(assumeNotNull(last_success_time)),
        'next_refresh_time', toString(assumeNotNull(next_refresh_time)),
        'duration_ms', toString(assumeNotNull(last_success_duration_ms)),
        'retry', toString(retry),
        'progress', toString(progress),
        'read_rows', toString(read_rows),
        'written_rows', toString(written_rows),
        'pipeline_type', 'rmv') AS LogAttributes
FROM system.view_refreshes;

-- ============================================================================
-- PART 4: REFRESHABLE MATERIALIZED VIEWS - METRICS
-- ============================================================================

-- 4.1 rmv_otel_gauge - Gauge Metrics
CREATE MATERIALIZED VIEW IF NOT EXISTS ${DATABASE_NAME}.rmv_otel_gauge
REFRESH EVERY ${REFRESH_INTERVAL_MINUTES} MINUTE
TO ${DATABASE_NAME}.otel_metrics_gauge
AS
-- Table metrics (rows, bytes, parts)
SELECT
    map('service.name', 'clickhouse-ingest-monitor',
        'service.version', '1.0.0',
        'deployment.environment', 'production',
        'clickhouse.service_id', extract(hostname(), 'c-([a-z]+-[a-z]+-[0-9]+)'),
        'clickhouse.replica', getMacro('replica'),
        'clickhouse.hostname', hostname()) AS ResourceAttributes,
    '' AS ResourceSchemaUrl,
    'clickhouse-ingest-monitor' AS ScopeName,
    '1.0.0' AS ScopeVersion,
    map() AS ScopeAttributes,
    toUInt32(0) AS ScopeDroppedAttrCount,
    '' AS ScopeSchemaUrl,
    'clickhouse-ingest-monitor' AS ServiceName,
    metric_name AS MetricName,
    '' AS MetricDescription,
    metric_unit AS MetricUnit,
    map('database', database, 'table', `table`) AS Attributes,
    now64(9) AS StartTimeUnix,
    now64(9) AS TimeUnix,
    metric_value AS Value,
    toUInt32(0) AS Flags,
    CAST([], 'Array(Map(LowCardinality(String), String))') AS `Exemplars.FilteredAttributes`,
    CAST([], 'Array(DateTime64(9))') AS `Exemplars.TimeUnix`,
    CAST([], 'Array(Float64)') AS `Exemplars.Value`,
    CAST([], 'Array(String)') AS `Exemplars.SpanId`,
    CAST([], 'Array(String)') AS `Exemplars.TraceId`
FROM (
    SELECT database, `table`, sum(rows) AS total_rows, sum(bytes_on_disk) AS total_bytes, count() AS part_count
    FROM system.parts
    WHERE active
      AND database NOT IN ('system', 'INFORMATION_SCHEMA', 'information_schema', '${DATABASE_NAME}')
    GROUP BY database, `table`
)
ARRAY JOIN
    ['table.rows', 'table.bytes', 'table.parts'] AS metric_name,
    ['rows', 'bytes', 'count'] AS metric_unit,
    [toFloat64(total_rows), toFloat64(total_bytes), toFloat64(part_count)] AS metric_value

UNION ALL

-- RMV refresh status metrics
SELECT
    map('service.name', 'clickhouse-ingest-monitor',
        'service.version', '1.0.0',
        'deployment.environment', 'production',
        'clickhouse.service_id', extract(hostname(), 'c-([a-z]+-[a-z]+-[0-9]+)'),
        'clickhouse.replica', getMacro('replica'),
        'clickhouse.hostname', hostname()) AS ResourceAttributes,
    '' AS ResourceSchemaUrl,
    'clickhouse-ingest-monitor' AS ScopeName,
    '1.0.0' AS ScopeVersion,
    map() AS ScopeAttributes,
    toUInt32(0) AS ScopeDroppedAttrCount,
    '' AS ScopeSchemaUrl,
    'clickhouse-ingest-monitor' AS ServiceName,
    metric_name AS MetricName,
    '' AS MetricDescription,
    metric_unit AS MetricUnit,
    map('database', database, 'mview', view, 'status', status) AS Attributes,
    now64(9) AS StartTimeUnix,
    now64(9) AS TimeUnix,
    metric_value AS Value,
    toUInt32(0) AS Flags,
    CAST([], 'Array(Map(LowCardinality(String), String))') AS `Exemplars.FilteredAttributes`,
    CAST([], 'Array(DateTime64(9))') AS `Exemplars.TimeUnix`,
    CAST([], 'Array(Float64)') AS `Exemplars.Value`,
    CAST([], 'Array(String)') AS `Exemplars.SpanId`,
    CAST([], 'Array(String)') AS `Exemplars.TraceId`
FROM (
    SELECT database, view, status, last_refresh_time, retry, progress
    FROM system.view_refreshes
    WHERE database NOT IN ('system', 'INFORMATION_SCHEMA', 'information_schema', '${DATABASE_NAME}')
)
ARRAY JOIN
    ['rmv.age_seconds', 'rmv.retry_count', 'rmv.progress'] AS metric_name,
    ['seconds', 'count', 'percent'] AS metric_unit,
    [toFloat64(dateDiff('second', last_refresh_time, now())), toFloat64(retry), progress] AS metric_value;

-- 4.2 rmv_otel_sum - Sum Metrics
CREATE MATERIALIZED VIEW IF NOT EXISTS ${DATABASE_NAME}.rmv_otel_sum
REFRESH EVERY ${REFRESH_INTERVAL_MINUTES} MINUTE
TO ${DATABASE_NAME}.otel_metrics_sum
AS
-- MView written metrics
SELECT
    map('service.name', 'clickhouse-ingest-monitor',
        'service.version', '1.0.0',
        'deployment.environment', 'production',
        'clickhouse.service_id', extract(hostname(), 'c-([a-z]+-[a-z]+-[0-9]+)'),
        'clickhouse.replica', getMacro('replica'),
        'clickhouse.hostname', hostname()) AS ResourceAttributes,
    '' AS ResourceSchemaUrl,
    'clickhouse-ingest-monitor' AS ScopeName,
    '1.0.0' AS ScopeVersion,
    map() AS ScopeAttributes,
    toUInt32(0) AS ScopeDroppedAttrCount,
    '' AS ScopeSchemaUrl,
    'clickhouse-ingest-monitor' AS ServiceName,
    metric_name AS MetricName,
    '' AS MetricDescription,
    metric_unit AS MetricUnit,
    map('database', database, 'mview', view) AS Attributes,
    now64(9) - INTERVAL ${REFRESH_INTERVAL_MINUTES} MINUTE AS StartTimeUnix,
    now64(9) AS TimeUnix,
    metric_value AS Value,
    toUInt32(0) AS Flags,
    CAST([], 'Array(Map(LowCardinality(String), String))') AS `Exemplars.FilteredAttributes`,
    CAST([], 'Array(DateTime64(9))') AS `Exemplars.TimeUnix`,
    CAST([], 'Array(Float64)') AS `Exemplars.Value`,
    CAST([], 'Array(String)') AS `Exemplars.SpanId`,
    CAST([], 'Array(String)') AS `Exemplars.TraceId`,
    toInt32(2) AS AggregationTemporality,
    true AS IsMonotonic
FROM (
    SELECT database, view, written_rows, written_bytes
    FROM system.view_refreshes
    WHERE database NOT IN ('system', 'INFORMATION_SCHEMA', 'information_schema', '${DATABASE_NAME}')
      AND written_rows > 0
)
ARRAY JOIN
    ['mview.written_rows', 'mview.written_bytes'] AS metric_name,
    ['rows', 'bytes'] AS metric_unit,
    [toFloat64(written_rows), toFloat64(written_bytes)] AS metric_value

UNION ALL

-- Part insert metrics
SELECT
    map('service.name', 'clickhouse-ingest-monitor',
        'service.version', '1.0.0',
        'deployment.environment', 'production',
        'clickhouse.service_id', extract(hostname(), 'c-([a-z]+-[a-z]+-[0-9]+)'),
        'clickhouse.replica', getMacro('replica'),
        'clickhouse.hostname', hostname()) AS ResourceAttributes,
    '' AS ResourceSchemaUrl,
    'clickhouse-ingest-monitor' AS ScopeName,
    '1.0.0' AS ScopeVersion,
    map() AS ScopeAttributes,
    toUInt32(0) AS ScopeDroppedAttrCount,
    '' AS ScopeSchemaUrl,
    'clickhouse-ingest-monitor' AS ServiceName,
    metric_name AS MetricName,
    '' AS MetricDescription,
    metric_unit AS MetricUnit,
    map('database', database, 'table', `table`) AS Attributes,
    now64(9) - INTERVAL ${LOOKBACK_INTERVAL_MINUTES} MINUTE AS StartTimeUnix,
    now64(9) AS TimeUnix,
    metric_value AS Value,
    toUInt32(0) AS Flags,
    CAST([], 'Array(Map(LowCardinality(String), String))') AS `Exemplars.FilteredAttributes`,
    CAST([], 'Array(DateTime64(9))') AS `Exemplars.TimeUnix`,
    CAST([], 'Array(Float64)') AS `Exemplars.Value`,
    CAST([], 'Array(String)') AS `Exemplars.SpanId`,
    CAST([], 'Array(String)') AS `Exemplars.TraceId`,
    toInt32(2) AS AggregationTemporality,
    true AS IsMonotonic
FROM (
    SELECT database, `table`, sum(rows) AS inserted_rows, sum(bytes_on_disk) AS inserted_bytes
    FROM system.parts
    WHERE active
      AND database NOT IN ('system', 'INFORMATION_SCHEMA', 'information_schema', '${DATABASE_NAME}')
      AND modification_time > now() - INTERVAL ${LOOKBACK_INTERVAL_MINUTES} MINUTE
    GROUP BY database, `table`
)
ARRAY JOIN
    ['part.rows_inserted', 'part.bytes_inserted'] AS metric_name,
    ['rows', 'bytes'] AS metric_unit,
    [toFloat64(inserted_rows), toFloat64(inserted_bytes)] AS metric_value;

-- 4.3 rmv_otel_histogram - Histogram Metrics
CREATE MATERIALIZED VIEW IF NOT EXISTS ${DATABASE_NAME}.rmv_otel_histogram
REFRESH EVERY ${REFRESH_INTERVAL_MINUTES} MINUTE
TO ${DATABASE_NAME}.otel_metrics_histogram
AS
SELECT
    map('service.name', 'clickhouse-ingest-monitor',
        'service.version', '1.0.0',
        'deployment.environment', 'production',
        'clickhouse.service_id', extract(hostname(), 'c-([a-z]+-[a-z]+-[0-9]+)'),
        'clickhouse.replica', getMacro('replica'),
        'clickhouse.hostname', hostname()) AS ResourceAttributes,
    '' AS ResourceSchemaUrl,
    'clickhouse-ingest-monitor' AS ScopeName,
    '1.0.0' AS ScopeVersion,
    map() AS ScopeAttributes,
    toUInt32(0) AS ScopeDroppedAttrCount,
    '' AS ScopeSchemaUrl,
    'clickhouse-ingest-monitor' AS ServiceName,
    'rmv.duration' AS MetricName,
    'RMV execution duration histogram' AS MetricDescription,
    'milliseconds' AS MetricUnit,
    map('database', database, 'mview', view) AS Attributes,
    now64(9) - INTERVAL ${REFRESH_INTERVAL_MINUTES} MINUTE AS StartTimeUnix,
    now64(9) AS TimeUnix,
    toUInt64(1) AS Count,
    toFloat64(assumeNotNull(last_success_duration_ms)) AS Sum,
    [toUInt64(if(assumeNotNull(last_success_duration_ms) <= 10, 1, 0)),
     toUInt64(if(assumeNotNull(last_success_duration_ms) > 10 AND assumeNotNull(last_success_duration_ms) <= 50, 1, 0)),
     toUInt64(if(assumeNotNull(last_success_duration_ms) > 50 AND assumeNotNull(last_success_duration_ms) <= 100, 1, 0)),
     toUInt64(if(assumeNotNull(last_success_duration_ms) > 100 AND assumeNotNull(last_success_duration_ms) <= 500, 1, 0)),
     toUInt64(if(assumeNotNull(last_success_duration_ms) > 500, 1, 0))] AS BucketCounts,
    [10.0, 50.0, 100.0, 500.0] AS ExplicitBounds,
    CAST([], 'Array(Map(LowCardinality(String), String))') AS `Exemplars.FilteredAttributes`,
    CAST([], 'Array(DateTime64(9))') AS `Exemplars.TimeUnix`,
    CAST([], 'Array(Float64)') AS `Exemplars.Value`,
    CAST([], 'Array(String)') AS `Exemplars.SpanId`,
    CAST([], 'Array(String)') AS `Exemplars.TraceId`,
    toUInt32(0) AS Flags,
    toFloat64(assumeNotNull(last_success_duration_ms)) AS Min,
    toFloat64(assumeNotNull(last_success_duration_ms)) AS Max,
    toInt32(2) AS AggregationTemporality
FROM system.view_refreshes
WHERE database NOT IN ('system', 'INFORMATION_SCHEMA', 'information_schema', '${DATABASE_NAME}')
  AND last_success_duration_ms IS NOT NULL;
